name: tubesfix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

assets:
  - goto/rect.jpg
  - assets/images/icon_bri.png
  - assets/images/icon_bni.png
  - assets/images/icon_bca.png
  - assets/images/icon_mandiri.png
  - assets/images/icon_bsi.png
  - assets/images/icon_bankpapua.png
  - assets/images/icon_dana.png
  - assets/images/icon_ovo.png
  - assets/images/icon_gopay.png
  - assets/images/icon_bpd
