name: tubesfix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+5
  permission_handler: ^10.0.0
  camera: ^0.10.0+2
  qr_flutter: ^4.1.0
  pdf: ^3.10.4
  printing: ^5.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl: ^0.18.0

flutter:
  assets:
    - assets/images/icon_bri.png
    - assets/images/icon_bni.png
    - assets/images/icon_bca.png
    - assets/images/icon_mandiri.png
    - assets/images/icon_bsi.png
    - assets/images/icon_bankpapua.png
    - assets/images/icon_bpd.png 
    - assets/images/icon_dana.png
    - assets/images/icon_ovo.png
    - assets/images/icon_gopay.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
          weight: 400
    - family: Mixage
      fonts:
        - asset: assets/fonts/Mixages/MixageITCStd-Bold.otf
          weight: 700
  uses-material-design: true
  
