name: tubesfix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+5
  permission_handler: ^10.0.0
  camera: ^0.10.0+2
  qr_flutter: ^4.1.0
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.0.11
  http: 1.2.2
  flutter_secure_storage: ^9.2.2
  vibration: ^1.7.6
  convex_bottom_bar:
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl: ^0.18.0
  url_launcher: ^6.1.5
  google_maps_flutter: ^2.2.4 
  geolocator: ^9.0.0 
  carousel_slider:

flutter:
  assets:
    - assets/images/icon_bri.png
    - assets/images/icon_bni.png
    - assets/images/icon_bca.png
    - assets/images/icon_mandiri.png
    - assets/images/icon_bsi.png
    - assets/images/icon_bankpapua.png
    - assets/images/icon_bpd.png 
    - assets/images/icon_dana.png
    - assets/images/icon_ovo.png
    - assets/images/icon_gopay.png
    - assets/images/08e70783-bb83-4d5a-ba05-3f828028147d.jpg
    - assets/images/60d04c08-ba9a-4a8b-81ee-fa28c1de0526.jpg
    - assets/images/750c4cb8-8b7e-49f4-9ad0-66c3108eac87.jpg
    - assets/images/afc4f05d-5efc-4f69-97ab-5dfc66e92b09.jpg
    - assets/images/f7f1e639-d2ac-4f98-9131-992c4a8d71f5.jpg
    - assets/images/awwa.jpg
    - assets/images/gohard.jpg
    - assets/images/man-getting-haircut.jpg
    - assets/images/maxresdefault.jpg
    - assets/sound/suara.mp3
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
          weight: 400
    - family: Mixage
      fonts:
        - asset: assets/fonts/Mixages/Mixage_ITC_Std_Bold.otf
          weight: 700
  uses-material-design: true
  
